### ISSUE TITLE
[BUG] TypeScript compilation does not work

### ISSUE THREAD

**Issue by Shamshiel** [alixaxel/chrome-aws-lambda#172]
## Environment
* `chrome-aws-lambda` Version: 5.3.1
* `puppeteer` / `puppeteer-core` Version: 5.3.1
* OS: Mac / Linux
* Node.js Version: 12.18.3
* Lambda / GCF Runtime: `nodejs12.x`

## Description
I'm using `chrome-aws-lambda` in combination with TypeScript. I have `chrome-aws-lambda` and `puppeteer-core` installed.

## Expected Behavior
If I use `tsc` my code compiles together with `aws-chrome-lambda` without errors.

## Current Behavior
If I use `tsc` it throws the following error:

```
node_modules/chrome-aws-lambda/source/index.d.ts:1:115 - error TS2307: Cannot find module 'puppeteer' or its corresponding type declarations.

1 import { BrowserOptions, DirectNavigationOptions, ElementHandle, NavigationOptions, ResourceType, Response } from 'puppeteer';
                                                                                                                    ~~~~~~~~~~~
node_modules/chrome-aws-lambda/source/index.d.ts:201:41 - error TS2307: Cannot find module 'puppeteer' or its corresponding type declarations.

201   static get puppeteer(): typeof import('puppeteer');
                                            ~~~~~~~~~~~
node_modules/chrome-aws-lambda/source/index.d.ts:211:36 - error TS2304: Cannot find name 'BrowserContext'.

211   export interface Browser extends BrowserContext {
                                       ~~~~~~~~~~~~~~
node_modules/chrome-aws-lambda/source/index.d.ts:218:16 - error TS2304: Cannot find name 'Target'.

218     targets(): Target[];
                   ~~~~~~
```

## Steps to Reproduce
Currently I have no easy steps for reproduction of the issue. I will try to come up with one.

## Possible Solution
Currently I can only compile my code with `tsc` if I add `"skipLibCheck": true` to my `tsconfig.json`

**Comment by alixaxel** [comment]
@Shamshiel The typings for this package extend the ones provided in `@types/puppeteer`.

Did you install that package locally? They are defined in `devDependencies` of this project.

**Comment by Shamshiel** [comment]
@alixaxel it works without `"skipLibCheck": true` if I install `@types/puppeteer` in my `devDependencies`

**Comment by startork** [comment]
I am running into exactly the same issue as Shamshiel but with puppeteer: ^7.0.4 and chrome-aws-lambda: ^7.0.0. However if I install `@types/puppeteer@^5.4.3` in `devDependencies` I still get the same error. 
I believe this is to do with puppeteer now exporting their own types. Is there any solution possible without adding `"skipLibCheck": true`?

**Comment by darrynhoskingluna** [comment]
I am also having this exact same issue. 
`"devDependencies": {
    "@types/aws-lambda": "^8.10.64",
    "@types/jest": "^26.0.14",
    "@types/puppeteer": "^5.4.3",
    "@types/puppeteer-core": "^5.4.0",
    "puppeteer": "^8.0.0",
    "serverless-bundle": "3.2.1",
    "serverless-dotenv-plugin": "^3.0.0",
    "serverless-offline": "^6.8.0"
  },
  "dependencies": {
    "@middy/core": "^1.5.2",
    "@middy/do-not-wait-for-empty-event-loop": "^1.5.2",
    "chrome-aws-lambda": "^7.0.0",
    "puppeteer-core": "^8.0.0"
  }`
  
If i remove the puppeteer dev dependancy the issue goes away but then i cant test locally. 
Following the workaround listed here https://github.com/alixaxel/chrome-aws-lambda/wiki/HOWTO:-Local-Development as i would like to be able run the project locally but once deployed will be using a lambda layer.

**Comment by alixaxel** [comment]
@startork Puppeteer 7.0.x had some issues with their own types, it was fixed on [puppeteer 7.1.0](https://github.com/puppeteer/puppeteer/releases/tag/v7.1.0). If you use `puppeteer` 7.1.x and `chrome-aws-lambda` 7.x you shouldn't have any issues and you should not need `@types/puppeteer`) for that matter.

@darrynhoskingluna As of version 7 (or 7.1 more specifically), puppeteer no longer needs `@types/puppeteer` or `@types/puppeteer-core`. Furthermore, as I mention in the README you need to keep the minor version in sync:

> This package is versioned based on the underlying puppeteer minor version.

I'm working on releasing `chrome-aws-lambda` v8.0 rewritten in TypeScript but if you don't want to wait you should use:

* chrome-aws-lambda: ^7.0.0
* puppeteer-core: ^7.1.0

**Comment by startork** [comment]
@alixaxel Unfortunately this doesn't seem to fix the issue, I am still getting the same error with the following versions. 
`"devDependencies": {
    "puppeteer": "^8.0.0",
    "typescript": "^4.0.3"
  },
  "dependencies": {
    "aws-sdk": "^2.765.0",
    "chrome-aws-lambda": "^7.0.0",
    "puppeteer-core": "^8.0.0"
}`

Looking at the puppeteer changelog it's looking like they are not going to be fixing this issue and making it worse by renaming BrowserOptions :) I assume this will be a case of just waiting for v8.0?

**Comment by sebsonjura** [comment]
is there any update on the isse? None of the provided solutions work.
